# -*- coding: utf-8 -*-
"""Robotika_Week2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MSoQ0ScgGfjX9rHvaVosFwiKO7eafmA1
"""

#!/usr/bin/env python3
import rospy

if __name__ == '__main__':
    rospy.init_node("test_node")

    rospy.loginfo("Test node has been started.")

    rate = rospy.Rate(10)
    while not rospy.is_shutdown():
        rospy.loginfo("Hello")
        rate.sleep()